[2024-03-31T23:31:06.758+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:31:06.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:31:06.760+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:31:06.760+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:31:06.777+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:31:06.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:31:06.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:31:06.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.039 seconds
[2024-03-31T23:31:37.094+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:31:37.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:31:37.096+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:31:37.095+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:31:37.104+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:31:37.102+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:31:37.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:31:37.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.028 seconds
[2024-03-31T23:32:08.029+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:32:08.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:32:08.032+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:32:08.031+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:32:08.044+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:32:08.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:32:08.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:32:08.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.040 seconds
[2024-03-31T23:32:38.108+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:32:38.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:32:38.110+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:32:38.110+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:32:38.130+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:32:38.121+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:32:38.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:32:38.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.048 seconds
[2024-03-31T23:33:08.194+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:33:08.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:33:08.196+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:33:08.196+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:33:08.211+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:33:08.207+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:33:08.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:33:08.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.045 seconds
[2024-03-31T23:33:38.352+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:33:38.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:33:38.354+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:33:38.354+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:33:38.370+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:33:38.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:33:38.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:33:38.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:34:08.465+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:34:08.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:34:08.468+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:34:08.467+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:34:08.481+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:34:08.478+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:34:08.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:34:08.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:34:38.551+0000] {processor.py:161} INFO - Started process (PID=439) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:34:38.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:34:38.554+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:34:38.553+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:34:38.567+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:34:38.564+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:34:38.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:34:38.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:35:08.650+0000] {processor.py:161} INFO - Started process (PID=495) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:35:08.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:35:08.652+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:35:08.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:35:08.661+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:35:08.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:35:08.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:35:08.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.027 seconds
[2024-03-31T23:35:38.949+0000] {processor.py:161} INFO - Started process (PID=551) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:35:38.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:35:38.952+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:35:38.951+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:35:38.965+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:35:38.963+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:35:38.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:35:38.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:36:09.146+0000] {processor.py:161} INFO - Started process (PID=607) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:36:09.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:36:09.148+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:36:09.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:36:09.157+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:36:09.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:36:09.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:36:09.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:36:39.396+0000] {processor.py:161} INFO - Started process (PID=663) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:36:39.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:36:39.398+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:36:39.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:36:39.410+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:36:39.407+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:36:39.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:36:39.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.031 seconds
[2024-03-31T23:37:09.487+0000] {processor.py:161} INFO - Started process (PID=719) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:37:09.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:37:09.489+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:37:09.489+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:37:09.501+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:37:09.499+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:37:09.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:37:09.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.033 seconds
[2024-03-31T23:37:39.572+0000] {processor.py:161} INFO - Started process (PID=776) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:37:39.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:37:39.574+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:37:39.574+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:37:39.587+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:37:39.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:37:39.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:37:39.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.039 seconds
[2024-03-31T23:38:09.789+0000] {processor.py:161} INFO - Started process (PID=832) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:38:09.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:38:09.792+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:38:09.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:38:09.806+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:38:09.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:38:09.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:38:09.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:38:39.868+0000] {processor.py:161} INFO - Started process (PID=888) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:38:39.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:38:39.871+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:38:39.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:38:39.883+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:38:39.880+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:38:39.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:38:39.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:39:10.071+0000] {processor.py:161} INFO - Started process (PID=944) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:39:10.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:39:10.073+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:39:10.073+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:39:10.085+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:39:10.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:39:10.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:39:10.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.029 seconds
[2024-03-31T23:39:40.302+0000] {processor.py:161} INFO - Started process (PID=1000) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:39:40.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:39:40.305+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:39:40.305+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:39:40.323+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:39:40.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:39:40.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:39:40.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.048 seconds
[2024-03-31T23:40:10.473+0000] {processor.py:161} INFO - Started process (PID=1056) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:40:10.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:40:10.477+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:40:10.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:40:10.496+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:40:10.491+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:40:10.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:40:10.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.050 seconds
[2024-03-31T23:40:40.655+0000] {processor.py:161} INFO - Started process (PID=1112) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:40:40.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:40:40.657+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:40:40.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:40:40.672+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:40:40.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:40:40.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:40:40.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.036 seconds
[2024-03-31T23:41:10.768+0000] {processor.py:161} INFO - Started process (PID=1168) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:41:10.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:41:10.770+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:41:10.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:41:10.786+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:41:10.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:41:10.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:41:10.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.040 seconds
[2024-03-31T23:41:40.855+0000] {processor.py:161} INFO - Started process (PID=1225) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:41:40.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:41:40.857+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:41:40.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:41:40.869+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:41:40.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:41:40.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:41:40.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.030 seconds
[2024-03-31T23:42:11.042+0000] {processor.py:161} INFO - Started process (PID=1281) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:42:11.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:42:11.044+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:42:11.044+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:42:11.058+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:42:11.056+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:42:11.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:42:11.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.033 seconds
[2024-03-31T23:42:41.337+0000] {processor.py:161} INFO - Started process (PID=1337) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:42:41.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:42:41.339+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:42:41.339+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:42:41.350+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:42:41.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:42:41.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:42:41.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.031 seconds
[2024-03-31T23:43:11.535+0000] {processor.py:161} INFO - Started process (PID=1393) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:43:11.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:43:11.537+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:43:11.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:43:11.549+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:43:11.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:43:11.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:43:11.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:43:41.793+0000] {processor.py:161} INFO - Started process (PID=1450) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:43:41.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:43:41.795+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:43:41.795+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:43:41.807+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:43:41.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:43:41.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:43:41.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:44:11.938+0000] {processor.py:161} INFO - Started process (PID=1506) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:44:11.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:44:11.941+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:44:11.940+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:44:11.955+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:44:11.953+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:44:11.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:44:11.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.045 seconds
[2024-03-31T23:44:42.079+0000] {processor.py:161} INFO - Started process (PID=1562) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:44:42.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:44:42.082+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:44:42.082+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:44:42.096+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:44:42.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:44:42.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:44:42.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.045 seconds
[2024-03-31T23:45:12.388+0000] {processor.py:161} INFO - Started process (PID=1618) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:45:12.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:45:12.391+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:45:12.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:45:12.406+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:45:12.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:45:12.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:45:12.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.047 seconds
[2024-03-31T23:45:42.669+0000] {processor.py:161} INFO - Started process (PID=1674) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:45:42.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:45:42.672+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:45:42.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:45:42.687+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:45:42.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:45:42.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:45:42.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.037 seconds
[2024-03-31T23:46:12.948+0000] {processor.py:161} INFO - Started process (PID=1730) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:46:12.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:46:12.950+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:46:12.950+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:46:12.963+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:46:12.961+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:46:12.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:46:12.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:46:43.179+0000] {processor.py:161} INFO - Started process (PID=1786) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:46:43.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:46:43.182+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:46:43.181+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:46:43.197+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:46:43.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:46:43.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:46:43.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.042 seconds
[2024-03-31T23:47:13.333+0000] {processor.py:161} INFO - Started process (PID=1842) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:47:13.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:47:13.335+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:47:13.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:47:13.348+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:47:13.346+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:47:13.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:47:13.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:47:44.247+0000] {processor.py:161} INFO - Started process (PID=1896) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:47:44.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:47:44.249+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:47:44.248+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:47:44.262+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:47:44.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:47:44.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:47:44.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.032 seconds
[2024-03-31T23:48:14.593+0000] {processor.py:161} INFO - Started process (PID=1952) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:48:14.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:48:14.595+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:48:14.595+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:48:14.607+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:48:14.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:48:14.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:48:14.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.032 seconds
[2024-03-31T23:48:44.799+0000] {processor.py:161} INFO - Started process (PID=2008) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:48:44.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:48:44.801+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:48:44.801+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:48:44.814+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:48:44.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:48:44.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:48:44.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.034 seconds
[2024-03-31T23:49:15.670+0000] {processor.py:161} INFO - Started process (PID=2064) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:49:15.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:49:15.673+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:49:15.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:49:15.687+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:49:15.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:49:15.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:49:15.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:49:45.840+0000] {processor.py:161} INFO - Started process (PID=2120) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:49:45.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:49:45.842+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:49:45.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:49:45.855+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:49:45.852+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:49:45.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:49:45.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.033 seconds
[2024-03-31T23:50:16.004+0000] {processor.py:161} INFO - Started process (PID=2176) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:50:16.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:50:16.006+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:50:16.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:50:16.021+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:50:16.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:50:16.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:50:16.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.042 seconds
[2024-03-31T23:50:46.368+0000] {processor.py:161} INFO - Started process (PID=2232) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:50:46.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:50:46.371+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:50:46.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:50:46.384+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:50:46.381+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:50:46.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:50:46.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.032 seconds
[2024-03-31T23:51:16.496+0000] {processor.py:161} INFO - Started process (PID=2288) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:51:16.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:51:16.499+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:51:16.499+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:51:16.509+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:51:16.507+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:51:16.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:51:16.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.039 seconds
[2024-03-31T23:51:46.619+0000] {processor.py:161} INFO - Started process (PID=2344) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:51:46.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:51:46.621+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:51:46.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:51:46.634+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:51:46.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:51:46.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:51:46.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.034 seconds
[2024-03-31T23:52:16.772+0000] {processor.py:161} INFO - Started process (PID=2400) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:52:16.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:52:16.774+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:52:16.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:52:16.789+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:52:16.786+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:52:16.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:52:16.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.045 seconds
[2024-03-31T23:52:46.874+0000] {processor.py:161} INFO - Started process (PID=2456) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:52:46.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:52:46.876+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:52:46.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:52:46.893+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:52:46.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:52:46.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:52:46.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.045 seconds
[2024-03-31T23:53:16.962+0000] {processor.py:161} INFO - Started process (PID=2512) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:53:16.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:53:16.964+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:53:16.964+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:53:16.980+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:53:16.977+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:53:16.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:53:16.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.034 seconds
[2024-03-31T23:53:47.030+0000] {processor.py:161} INFO - Started process (PID=2568) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:53:47.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:53:47.033+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:53:47.032+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:53:47.046+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:53:47.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:53:47.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:53:47.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.032 seconds
[2024-03-31T23:54:17.105+0000] {processor.py:161} INFO - Started process (PID=2624) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:54:17.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:54:17.107+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:54:17.106+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:54:17.119+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:54:17.117+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:54:17.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:54:17.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.041 seconds
[2024-03-31T23:54:47.245+0000] {processor.py:161} INFO - Started process (PID=2680) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:54:47.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:54:47.248+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:54:47.247+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:54:47.261+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:54:47.258+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:54:47.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:54:47.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:55:17.475+0000] {processor.py:161} INFO - Started process (PID=2736) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:55:17.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:55:17.477+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:55:17.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:55:17.493+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:55:17.491+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:55:17.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:55:17.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.043 seconds
[2024-03-31T23:55:47.544+0000] {processor.py:161} INFO - Started process (PID=2792) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:55:47.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:55:47.547+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:55:47.546+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:55:47.558+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:55:47.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:55:47.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:55:47.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.040 seconds
[2024-03-31T23:56:17.658+0000] {processor.py:161} INFO - Started process (PID=2848) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:56:17.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:56:17.660+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:56:17.660+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:56:17.672+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:56:17.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:56:17.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:56:17.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.040 seconds
[2024-03-31T23:56:47.914+0000] {processor.py:161} INFO - Started process (PID=2904) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:56:47.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:56:47.916+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:56:47.916+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:56:47.932+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:56:47.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:56:47.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:56:47.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.045 seconds
[2024-03-31T23:57:18.200+0000] {processor.py:161} INFO - Started process (PID=2960) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:57:18.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:57:18.202+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:57:18.202+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:57:18.216+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:57:18.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:57:18.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:57:18.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.046 seconds
[2024-03-31T23:57:48.442+0000] {processor.py:161} INFO - Started process (PID=3016) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:57:48.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:57:48.445+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:57:48.445+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:57:48.458+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:57:48.456+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:57:48.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:57:48.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.042 seconds
[2024-03-31T23:58:18.566+0000] {processor.py:161} INFO - Started process (PID=3072) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:58:18.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:58:18.568+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:58:18.568+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:58:18.585+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:58:18.581+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:58:18.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:58:18.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.044 seconds
[2024-03-31T23:58:49.086+0000] {processor.py:161} INFO - Started process (PID=3128) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:58:49.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:58:49.089+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:58:49.088+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:58:49.104+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:58:49.100+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:58:49.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:58:49.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.044 seconds
[2024-03-31T23:59:19.879+0000] {processor.py:161} INFO - Started process (PID=3184) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:59:19.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:59:19.885+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:59:19.884+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:59:19.898+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:59:19.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:59:19.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:59:19.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.046 seconds
[2024-03-31T23:59:50.185+0000] {processor.py:161} INFO - Started process (PID=3240) to work on /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:59:50.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/testing_req_dag.py for tasks to queue
[2024-03-31T23:59:50.187+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:59:50.187+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:59:50.195+0000] {logging_mixin.py:188} INFO - [2024-03-31T23:59:50.194+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/testing_req_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/testing_req_dag.py", line 4, in <module>
    from airflow.operations.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.operations'
[2024-03-31T23:59:50.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/testing_req_dag.py
[2024-03-31T23:59:50.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/testing_req_dag.py took 0.035 seconds
